version: "3.9"
services:
  ros2_dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "10000:10000"   # listen for Unity
      - "9090:9090"     
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - ../dev_ws:/home/ros/dev_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    user: ros
    command: bash
